// paises_data.dart - Datos estáticos de los 48 países del Mundial 2026

class PaisData {
  final String capital;
  final String continente;
  final int habitantes;
  final List<String> ciudades;
  final List<String> clubes;
  final String entrenador;
  final int rankingFifa;
  final List<String> curiosidades;

  const PaisData({
    required this.capital,
    required this.continente,
    required this.habitantes,
    required this.ciudades,
    required this.clubes,
    required this.entrenador,
    required this.rankingFifa,
    required this.curiosidades,
  });
}

const Map<String, PaisData> kPaisesData = {
  'Argentina': PaisData(
    capital: 'Buenos Aires', continente: 'América del Sur', habitantes: 45600000,
    ciudades: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'Tucumán'],
    clubes: ['Boca Juniors', 'River Plate', 'Racing Club', 'Independiente', 'San Lorenzo'],
    entrenador: 'Lionel Scaloni', rankingFifa: 1,
    curiosidades: [
      'Campeona del mundo en 1978, 1986 y 2022',
      'Cuna de Lionel Messi y Diego Maradona, dos de los mejores jugadores de la historia',
      'El tango es el baile nacional y Patrimonio Cultural Inmaterial de la UNESCO',
      'Buenos Aires es conocida como el "París de Sudamérica"',
    ],
  ),
  'Francia': PaisData(
    capital: 'París', continente: 'Europa', habitantes: 68400000,
    ciudades: ['París', 'Marsella', 'Lyon', 'Toulouse', 'Niza'],
    clubes: ['Paris Saint-Germain', 'Olympique de Marseille', 'Olympique Lyonnais', 'Monaco', 'Lille'],
    entrenador: 'Didier Deschamps', rankingFifa: 2,
    curiosidades: [
      'Campeona del mundo en 1998 y 2018',
      'Torre Eiffel, el Louvre y Versalles son sus monumentos más famosos',
      'País con más estrellas Michelin del mundo en gastronomía',
      'Kylian Mbappé, máximo goleador del Mundial 2022, es francés',
    ],
  ),
  'España': PaisData(
    capital: 'Madrid', continente: 'Europa', habitantes: 47400000,
    ciudades: ['Madrid', 'Barcelona', 'Valencia', 'Sevilla', 'Bilbao'],
    clubes: ['Real Madrid', 'FC Barcelona', 'Atlético de Madrid', 'Sevilla FC', 'Athletic Club'],
    entrenador: 'Luis de la Fuente', rankingFifa: 3,
    curiosidades: [
      'Campeona del mundo en 2010 y de Europa en 1964, 2008, 2012 y 2024',
      'La Liga es una de las competiciones de clubes más prestigiosas del mundo',
      'País conocido por el flamenco, la paella y la arquitectura de Gaudí',
      'Cuna del tiki-taka, estilo de juego que revolucionó el fútbol mundial',
    ],
  ),
  'Inglaterra': PaisData(
    capital: 'Londres', continente: 'Europa', habitantes: 56500000,
    ciudades: ['Londres', 'Manchester', 'Birmingham', 'Liverpool', 'Leeds'],
    clubes: ['Manchester City', 'Arsenal', 'Chelsea', 'Liverpool', 'Manchester United'],
    entrenador: 'Lee Carsley', rankingFifa: 4,
    curiosidades: [
      'Inventores del fútbol moderno, campeones del mundo en 1966',
      'La Premier League es la liga más seguida del mundo',
      'Wembley, con capacidad para 90.000 espectadores, es uno de los estadios más famosos',
      'País del té, los pubs y la familia real británica',
    ],
  ),
  'Brasil': PaisData(
    capital: 'Brasilia', continente: 'América del Sur', habitantes: 215000000,
    ciudades: ['São Paulo', 'Río de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza'],
    clubes: ['Flamengo', 'Corinthians', 'Palmeiras', 'São Paulo FC', 'Fluminense'],
    entrenador: 'Dorival Júnior', rankingFifa: 5,
    curiosidades: [
      'Único país en haber jugado todos los Mundiales, campeón en 5 ocasiones',
      'El carnaval de Río de Janeiro es uno de los espectáculos más famosos del mundo',
      'País con la mayor selva tropical del mundo: el Amazonas',
      'Pelé, considerado por muchos el mejor futbolista de la historia, es brasileño',
    ],
  ),
  'Portugal': PaisData(
    capital: 'Lisboa', continente: 'Europa', habitantes: 10300000,
    ciudades: ['Lisboa', 'Oporto', 'Braga', 'Setúbal', 'Coimbra'],
    clubes: ['Benfica', 'FC Porto', 'Sporting CP', 'SC Braga', 'Vitória SC'],
    entrenador: 'Roberto Martínez', rankingFifa: 6,
    curiosidades: [
      'Campeón de Europa en 2016 y de la Nations League en 2019',
      'Cristiano Ronaldo, uno de los mejores jugadores de la historia, es portugués',
      'País pionero en las Grandes Navegaciones con gran influencia cultural global',
      'El fado es el género musical tradicional portugués, Patrimonio de la UNESCO',
    ],
  ),
  'Bélgica': PaisData(
    capital: 'Bruselas', continente: 'Europa', habitantes: 11600000,
    ciudades: ['Bruselas', 'Amberes', 'Gante', 'Brujas', 'Lieja'],
    clubes: ['Club Brujas', 'Anderlecht', 'Standard de Lieja', 'Gante', 'Union SG'],
    entrenador: 'Domenico Tedesco', rankingFifa: 7,
    curiosidades: [
      'La Generación Dorada belga fue considerada la mejor del mundo entre 2015 y 2022',
      'País conocido por el chocolate, las patatas fritas y la cerveza',
      'Sede de la Unión Europea y la OTAN en Bruselas',
      'Kevin De Bruyne es uno de los mejores centrocampistas de su generación',
    ],
  ),
  'Países Bajos': PaisData(
    capital: 'Ámsterdam', continente: 'Europa', habitantes: 17900000,
    ciudades: ['Ámsterdam', 'Rotterdam', 'La Haya', 'Utrecht', 'Eindhoven'],
    clubes: ['Ajax', 'Feyenoord', 'PSV Eindhoven', 'AZ Alkmaar', 'Twente'],
    entrenador: 'Ronald Koeman', rankingFifa: 8,
    curiosidades: [
      'Tres veces finalista del Mundial (1974, 1978 y 2010) sin conseguir el título',
      'Cuna del fútbol total, revolucionario sistema táctico de los años 70',
      'País de los tulipanes, los molinos de viento y las bicicletas',
      'Johan Cruyff, icono del fútbol mundial, es neerlandés',
    ],
  ),
  'Alemania': PaisData(
    capital: 'Berlín', continente: 'Europa', habitantes: 84400000,
    ciudades: ['Berlín', 'Múnich', 'Hamburgo', 'Colonia', 'Frankfurt'],
    clubes: ['Bayern Múnich', 'Borussia Dortmund', 'RB Leipzig', 'Bayer Leverkusen', 'Borussia M\'gladbach'],
    entrenador: 'Julian Nagelsmann', rankingFifa: 9,
    curiosidades: [
      'Campeona del mundo en 1954, 1974, 1990 y 2014',
      'La Bundesliga es conocida por su ambiente en los estadios y precios accesibles',
      'País del automóvil: sede de BMW, Mercedes-Benz, Volkswagen y Audi',
      'El Oktoberfest de Múnich es la mayor fiesta de la cerveza del mundo',
    ],
  ),
  'Italia': PaisData(
    capital: 'Roma', continente: 'Europa', habitantes: 59200000,
    ciudades: ['Roma', 'Milán', 'Nápoles', 'Turín', 'Florencia'],
    clubes: ['Juventus', 'Inter de Milán', 'AC Milan', 'Nápoles', 'AS Roma'],
    entrenador: 'Luciano Spalletti', rankingFifa: 10,
    curiosidades: [
      'Campeona del mundo en 1934, 1938, 1982 y 2006',
      'Cuna del Renacimiento y con el mayor número de Patrimonio de la UNESCO',
      'La gastronomía italiana (pizza, pasta) es una de las más populares del mundo',
      'El calcio es una pasión nacional con históricas rivalidades entre clubes',
    ],
  ),
  'Croacia': PaisData(
    capital: 'Zagreb', continente: 'Europa', habitantes: 3900000,
    ciudades: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'],
    clubes: ['Dinamo Zagreb', 'Hajduk Split', 'HNK Rijeka', 'NK Osijek'],
    entrenador: 'Zlatko Dalić', rankingFifa: 11,
    curiosidades: [
      'Finalista del Mundial 2018, semifinalista en 1998 y 2022',
      'Luka Modrić, Balón de Oro 2018, es el mejor jugador de la historia croata',
      'País de más de 1.200 islas en el mar Adriático',
      'La corbata fue inventada en Croacia, de ahí su nombre (cravate en francés)',
    ],
  ),
  'Marruecos': PaisData(
    capital: 'Rabat', continente: 'África', habitantes: 37500000,
    ciudades: ['Casablanca', 'Rabat', 'Fez', 'Marrakech', 'Tánger'],
    clubes: ['Wydad Casablanca', 'Raja Casablanca', 'FUS Rabat', 'FAR Rabat'],
    entrenador: 'Walid Regragui', rankingFifa: 12,
    curiosidades: [
      'Primera selección africana en llegar a semifinales de un Mundial (Qatar 2022)',
      'Sede del Mundial 2030 junto a España y Portugal',
      'País conocido por sus medinas, zocos y la arquitectura árabe-bereber',
      'El couscous es su plato nacional y Patrimonio Cultural Inmaterial de la UNESCO',
    ],
  ),
  'Estados Unidos': PaisData(
    capital: 'Washington D.C.', continente: 'América del Norte', habitantes: 335000000,
    ciudades: ['Nueva York', 'Los Ángeles', 'Chicago', 'Houston', 'Miami'],
    clubes: ['LA Galaxy', 'Inter Miami', 'Seattle Sounders', 'Atlanta United', 'NYCFC'],
    entrenador: 'Mauricio Pochettino', rankingFifa: 13,
    curiosidades: [
      'Organizó el Mundial de 1994, el más exitoso en asistencia hasta entonces',
      'La MLS ha crecido enormemente con la llegada de estrellas como Messi y Beckham',
      'País con más ligas deportivas profesionales del mundo',
      'Sede de 9 estadios del Mundial 2026, más que ningún otro país anfitrión',
    ],
  ),
  'México': PaisData(
    capital: 'Ciudad de México', continente: 'América del Norte', habitantes: 130000000,
    ciudades: ['Ciudad de México', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana'],
    clubes: ['Club América', 'Chivas de Guadalajara', 'Cruz Azul', 'Pumas UNAM', 'Tigres UANL'],
    entrenador: 'Javier Aguirre', rankingFifa: 14,
    curiosidades: [
      'Único país en organizar tres Mundiales (1970, 1986 y 2026)',
      'El Estadio Azteca es el único que ha albergado dos finales mundialistas',
      'País con una de las gastronomías más ricas del mundo, Patrimonio de la UNESCO',
      'Cuna de civilizaciones como los aztecas y los mayas',
    ],
  ),
  'Colombia': PaisData(
    capital: 'Bogotá', continente: 'América del Sur', habitantes: 51900000,
    ciudades: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'],
    clubes: ['Millonarios', 'Atlético Nacional', 'América de Cali', 'Junior', 'Santa Fe'],
    entrenador: 'Néstor Lorenzo', rankingFifa: 15,
    curiosidades: [
      'James Rodríguez fue el máximo goleador del Mundial 2014 con 6 goles',
      'País conocido por el café, las flores y la biodiversidad',
      'La cumbia y el vallenato son géneros musicales originarios de Colombia',
      'Falcao, uno de los mejores delanteros de su generación, es colombiano',
    ],
  ),
  'Uruguay': PaisData(
    capital: 'Montevideo', continente: 'América del Sur', habitantes: 3500000,
    ciudades: ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandú', 'Las Piedras'],
    clubes: ['Peñarol', 'Nacional', 'Defensor Sporting', 'Danubio', 'Liverpool FC Uruguay'],
    entrenador: 'Marcelo Bielsa', rankingFifa: 16,
    curiosidades: [
      'Campeón del primer Mundial (1930) y del Mundial de 1950',
      'A pesar de su pequeño tamaño, es una de las selecciones más exitosas de Sudamérica',
      'País con el mayor consumo de carne per cápita del mundo',
      'Primer país del mundo en legalizar el cannabis a nivel nacional',
    ],
  ),
  'Japón': PaisData(
    capital: 'Tokio', continente: 'Asia', habitantes: 125000000,
    ciudades: ['Tokio', 'Osaka', 'Nagoya', 'Sapporo', 'Fukuoka'],
    clubes: ['Kashima Antlers', 'Urawa Red Diamonds', 'Gamba Osaka', 'Vissel Kobe', 'Yokohama F. Marinos'],
    entrenador: 'Hajime Moriyasu', rankingFifa: 17,
    curiosidades: [
      'Coorganizador del Mundial 2002, llegando a cuartos de final',
      'La J-League fue pionera en el fútbol asiático moderno desde 1993',
      'País conocido por la tecnología, el anime, el sushi y el monte Fuji',
      'Shinji Kagawa y Hidetoshi Nakata son sus jugadores más internacionales',
    ],
  ),
  'Senegal': PaisData(
    capital: 'Dakar', continente: 'África', habitantes: 17200000,
    ciudades: ['Dakar', 'Touba', 'Thiès', 'Kaolack', 'Ziguinchor'],
    clubes: ['Generation Foot', 'AS Pikine', 'Teungueth FC', 'Casa Sports'],
    entrenador: 'Aliou Cissé', rankingFifa: 18,
    curiosidades: [
      'Campeón de África en 2021 y 2022, finalista en 2002',
      'Semifinalista del Mundial 2002, mejor resultado africano hasta Qatar 2022',
      'Sadio Mané, ganador del Balón de Oro Africano, es senegalés',
      'País conocido por la música mbalax y el lucha libre tradicional',
    ],
  ),
  'Ecuador': PaisData(
    capital: 'Quito', continente: 'América del Sur', habitantes: 18000000,
    ciudades: ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala'],
    clubes: ['Barcelona SC', 'Emelec', 'Liga de Quito', 'Independiente del Valle', 'Deportivo Cuenca'],
    entrenador: 'Sebastián Beccacece', rankingFifa: 19,
    curiosidades: [
      'País que da nombre a la línea del Ecuador que divide el planeta',
      'Las Islas Galápagos, donde Darwin desarrolló su teoría de la evolución, son ecuatorianas',
      'Enner Valencia es el máximo goleador histórico de la selección',
      'Ecuador abrió el Mundial de Qatar 2022 con victoria ante el país anfitrión',
    ],
  ),
  'Suiza': PaisData(
    capital: 'Berna', continente: 'Europa', habitantes: 8700000,
    ciudades: ['Zúrich', 'Ginebra', 'Basilea', 'Berna', 'Lausana'],
    clubes: ['FC Basel', 'Young Boys', 'FC Zürich', 'Servette', 'Grasshoppers'],
    entrenador: 'Murat Yakin', rankingFifa: 20,
    curiosidades: [
      'País neutral desde 1815, sede de organismos internacionales como la ONU y la FIFA',
      'Conocida por sus relojes, el chocolate, el queso y los bancos',
      'Xherdan Shaqiri es uno de los jugadores más conocidos internacionalmente',
      'País con cuatro idiomas oficiales: alemán, francés, italiano y romanche',
    ],
  ),
  'Corea del Sur': PaisData(
    capital: 'Seúl', continente: 'Asia', habitantes: 51700000,
    ciudades: ['Seúl', 'Busan', 'Incheon', 'Daegu', 'Daejeon'],
    clubes: ['Jeonbuk Hyundai Motors', 'Ulsan HD', 'Seongnam FC', 'Suwon Samsung Bluewings'],
    entrenador: 'Hong Myung-bo', rankingFifa: 22,
    curiosidades: [
      'Semifinalista del Mundial 2002, mejor resultado asiático en la historia',
      'Son Heung-min es uno de los mejores extremos del mundo',
      'País del K-pop, los dramas coreanos y la gastronomía del kimchi',
      'Uno de los países con mayor velocidad de internet del mundo',
    ],
  ),
  'Canadá': PaisData(
    capital: 'Ottawa', continente: 'América del Norte', habitantes: 38900000,
    ciudades: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton'],
    clubes: ['Toronto FC', 'CF Montréal', 'Vancouver Whitecaps', 'CF Atlético Ottawa'],
    entrenador: 'Jesse Marsch', rankingFifa: 23,
    curiosidades: [
      'Debutante en el Mundial 2022 tras 36 años de ausencia',
      'El hockey sobre hielo es el deporte nacional, aunque el fútbol crece rápidamente',
      'Segundo país más grande del mundo por superficie',
      'País bilingüe (inglés y francés) con gran diversidad cultural',
    ],
  ),
  'Túnez': PaisData(
    capital: 'Túnez', continente: 'África', habitantes: 12000000,
    ciudades: ['Túnez', 'Sfax', 'Sousse', 'Kairouan', 'Biserta'],
    clubes: ['Espérance Sportive de Tunis', 'Club Africain', 'Étoile Sportive du Sahel', 'CS Sfaxien'],
    entrenador: 'Jalel Kadri', rankingFifa: 24,
    curiosidades: [
      'Única selección africana en vencer a Francia en un Mundial (1978)',
      'País con la mayor cantidad de sitios romanos del mundo fuera de Italia',
      'El cine tunecino tiene gran reconocimiento en los festivales internacionales',
      'Cuna de Aníbal, el famoso general cartaginés que cruzó los Alpes con elefantes',
    ],
  ),
  'Australia': PaisData(
    capital: 'Canberra', continente: 'Oceanía', habitantes: 26500000,
    ciudades: ['Sídney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaida'],
    clubes: ['Melbourne City', 'Sydney FC', 'Melbourne Victory', 'Western Sydney Wanderers'],
    entrenador: 'Tony Popovic', rankingFifa: 25,
    curiosidades: [
      'Semifinalista del Mundial 2022 con la generación de Socceroos más talentosa',
      'País que alberga animales únicos como el canguro, el koala y el ornitorrinco',
      'La Gran Barrera de Coral es el mayor sistema de arrecifes del mundo',
      'Sam Kerr es la máxima goleadora histórica de la selección femenina australiana',
    ],
  ),
  'Austria': PaisData(
    capital: 'Viena', continente: 'Europa', habitantes: 9100000,
    ciudades: ['Viena', 'Graz', 'Linz', 'Salzburgo', 'Innsbruck'],
    clubes: ['Red Bull Salzburg', 'Rapid Viena', 'FK Austria Viena', 'Sturm Graz', 'LASK'],
    entrenador: 'Ralf Rangnick', rankingFifa: 26,
    curiosidades: [
      'Tercera en el Mundial de 1954, su mejor resultado histórico',
      'País de Mozart, Beethoven, Freud y Klimt, capital cultural de Europa',
      'Viena es considerada la ciudad con mayor calidad de vida del mundo',
      'David Alaba es el jugador austríaco más conocido internacionalmente',
    ],
  ),
  'Turquía': PaisData(
    capital: 'Ankara', continente: 'Europa/Asia', habitantes: 85200000,
    ciudades: ['Estambul', 'Ankara', 'Esmirna', 'Bursa', 'Adana'],
    clubes: ['Galatasaray', 'Fenerbahçe', 'Beşiktaş', 'Trabzonspor', 'Başakşehir'],
    entrenador: 'Vincenzo Montella', rankingFifa: 27,
    curiosidades: [
      'Semifinalista del Mundial 2002, su mejor resultado histórico',
      'País que une Europa y Asia, con Estambul dividida entre dos continentes',
      'Hakan Çalhanoğlu y Arda Güler son sus estrellas actuales',
      'País conocido por el kebab, el baklava y las mezquitas',
    ],
  ),
  'Irán': PaisData(
    capital: 'Teherán', continente: 'Asia', habitantes: 88600000,
    ciudades: ['Teherán', 'Mascad', 'Isfahán', 'Karaj', 'Tabriz'],
    clubes: ['Persépolis', 'Esteghlal', 'Tractor', 'Sepahan', 'Foolad'],
    entrenador: 'Amir Ghalenoei', rankingFifa: 28,
    curiosidades: [
      'Selección más participante de Asia en la Copa del Mundo con 7 participaciones',
      'Ali Daei fue el máximo goleador internacional del mundo durante años con 109 goles',
      'País con una de las civilizaciones más antiguas del mundo, antigua Persia',
      'Conocido por sus alfombras, la arquitectura persa y el zoroastrismo',
    ],
  ),
  'Noruega': PaisData(
    capital: 'Oslo', continente: 'Europa', habitantes: 5500000,
    ciudades: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger', 'Tromsø'],
    clubes: ['Rosenborg', 'Molde', 'Brann', 'Bodø/Glimt', 'Vålerenga'],
    entrenador: 'Ståle Solbakken', rankingFifa: 29,
    curiosidades: [
      'Erling Haaland es el delantero más temido del mundo en la actualidad',
      'País conocido por los fiordos, la aurora boreal y los vikingos',
      'Noruega es el mayor productor de petróleo de Europa occidental',
      'País con uno de los índices de desarrollo humano más altos del mundo',
    ],
  ),
  'Catar': PaisData(
    capital: 'Doha', continente: 'Asia', habitantes: 2900000,
    ciudades: ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal'],
    clubes: ['Al-Sadd', 'Al-Duhail', 'Al-Rayyan', 'Al-Arabi', 'Al-Gharafa'],
    entrenador: 'Iñaki Alonso', rankingFifa: 30,
    curiosidades: [
      'Anfitrión del Mundial 2022, primer país árabe en organizarlo',
      'País con mayor renta per cápita del mundo gracias al gas natural',
      'Sede de Al Jazeera, el canal de noticias árabe más influyente',
      'El desierto ocupa casi todo su territorio, con temperaturas de hasta 50ºC',
    ],
  ),
  'Arabia Saudí': PaisData(
    capital: 'Riad', continente: 'Asia', habitantes: 35000000,
    ciudades: ['Riad', 'Yeda', 'La Meca', 'Medina', 'Dammam'],
    clubes: ['Al-Hilal', 'Al-Nassr', 'Al-Ittihad', 'Al-Ahli'],
    entrenador: 'Hervé Renard', rankingFifa: 31,
    curiosidades: [
      'Venció a Argentina en el Mundial 2022 en una de las mayores sorpresas de la historia',
      'País de La Meca y Medina, las ciudades más sagradas del Islam',
      'Cristiano Ronaldo juega en la liga saudí, que ha fichado muchas estrellas mundiales',
      'Arabia Saudí organizará el Mundial 2034',
    ],
  ),
  'Ghana': PaisData(
    capital: 'Acra', continente: 'África', habitantes: 33500000,
    ciudades: ['Acra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Sunyani'],
    clubes: ['Asante Kotoko', 'Hearts of Oak', 'Medeama SC', 'Aduana Stars'],
    entrenador: 'Otto Addo', rankingFifa: 32,
    curiosidades: [
      'Cuartofinalista del Mundial 2010, eliminado por Uruguay en polémica mano de Suárez',
      'Primer país subsahariano en independizarse (1957)',
      'El chocolate que comemos viene en gran parte del cacao ghanés',
      'Michael Essien y Asamoah Gyan son sus jugadores más célebres',
    ],
  ),
  'Argelia': PaisData(
    capital: 'Argel', continente: 'África', habitantes: 45600000,
    ciudades: ['Argel', 'Orán', 'Constantine', 'Annaba', 'Blida'],
    clubes: ['CR Belouizdad', 'USM Alger', 'MC Alger', 'ES Sétif', 'JS Kabylie'],
    entrenador: 'Vladimir Petković', rankingFifa: 33,
    curiosidades: [
      'Campeón de África en 2019, su segunda estrella continental',
      'País más grande de África y del mundo árabe por superficie',
      'Zinédine Zidane, uno de los mejores jugadores de la historia, tiene origen argelino',
      'El Sahara, el desierto más grande del mundo, cubre la mayor parte del país',
    ],
  ),
  'Costa de Marfil': PaisData(
    capital: 'Yamoussoukro', continente: 'África', habitantes: 27500000,
    ciudades: ['Abiyán', 'Yamoussoukro', 'Bouaké', 'Daloa', 'Korhogo'],
    clubes: ['ASEC Mimosas', 'Africa Sports', 'Sporting Club de Gagnoa'],
    entrenador: 'Emerse Faé', rankingFifa: 34,
    curiosidades: [
      'Campeón de África en 1992 y 2015',
      'Didier Drogba es el mayor ídolo del fútbol marfileño de todos los tiempos',
      'Mayor productor mundial de cacao, con el 40% de la producción global',
      'País con gran biodiversidad, con elefantes en su escudo nacional',
    ],
  ),
  'República Checa': PaisData(
    capital: 'Praga', continente: 'Europa', habitantes: 10900000,
    ciudades: ['Praga', 'Brno', 'Ostrava', 'Pilsen', 'Liberec'],
    clubes: ['Slavia Praga', 'Sparta Praga', 'Viktoria Pilsen', 'AC Baník Ostrava'],
    entrenador: 'Ivan Hašek', rankingFifa: 35,
    curiosidades: [
      'Como Checoslovaquia fue finalista del Mundial 1934 y 1962',
      'Praga es una de las ciudades medievales mejor conservadas de Europa',
      'País con mayor consumo de cerveza per cápita del mundo',
      'Patrik Schick fue el segundo máximo goleador de la Eurocopa 2020',
    ],
  ),
  'Escocia': PaisData(
    capital: 'Edimburgo', continente: 'Europa', habitantes: 5500000,
    ciudades: ['Glasgow', 'Edimburgo', 'Aberdeen', 'Dundee', 'Inverness'],
    clubes: ['Celtic', 'Rangers', 'Aberdeen', 'Heart of Midlothian', 'Hibernian'],
    entrenador: 'Steve Clarke', rankingFifa: 36,
    curiosidades: [
      'País donde se jugó el primer partido internacional de fútbol de la historia (1872)',
      'Tierra del whisky escocés, las gaitas y los Highlands',
      'El Celtic y el Rangers protagonizan el "Old Firm", uno de los derbis más apasionados',
      'El golf moderno fue inventado en Escocia en el siglo XV',
    ],
  ),
  'Paraguay': PaisData(
    capital: 'Asunción', continente: 'América del Sur', habitantes: 7400000,
    ciudades: ['Asunción', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiatá'],
    clubes: ['Olimpia', 'Cerro Porteño', 'Libertad', 'Guaraní', 'Sol de América'],
    entrenador: 'Gustavo Alfaro', rankingFifa: 40,
    curiosidades: [
      'Cuartofinalista del Mundial 2010, su mejor resultado desde 1954',
      'País sin salida al mar, conocido como el "corazón de América del Sur"',
      'El guaraní es el idioma más hablado junto al español, lengua oficial',
      'José Luis Chilavert fue uno de los mejores porteros-goleadores de la historia',
    ],
  ),
  'Egipto': PaisData(
    capital: 'El Cairo', continente: 'África', habitantes: 105000000,
    ciudades: ['El Cairo', 'Alejandría', 'Giza', 'Luxor', 'Asuán'],
    clubes: ['Al-Ahly', 'Zamalek', 'Pyramids FC', 'Al-Ismaily', 'El-Masry'],
    entrenador: 'Hossam Hassan', rankingFifa: 41,
    curiosidades: [
      'Mohamed Salah es el jugador africano más reconocido del mundo actualmente',
      'País de las pirámides, la esfinge y la civilización más antigua del mundo',
      'El Al-Ahly es el club más laureado de África',
      'El río Nilo, el más largo del mundo, atraviesa todo el país',
    ],
  ),
  'Irak': PaisData(
    capital: 'Bagdad', continente: 'Asia', habitantes: 41200000,
    ciudades: ['Bagdad', 'Basora', 'Mosul', 'Erbil', 'Nayaf'],
    clubes: ['Al-Zawraa', 'Al-Shorta', 'Al-Quwa Al-Jawiya', 'Arbil SC'],
    entrenador: 'Jesús Casas', rankingFifa: 42,
    curiosidades: [
      'Campeón de Asia en 2007, su mayor logro internacional',
      'Mesopotamia, la "cuna de la civilización", está en el actual territorio iraquí',
      'País con las reservas de petróleo más grandes del mundo',
      'El río Tigris y el Éufrates, bíblicos, atraviesan el país',
    ],
  ),
  'Panamá': PaisData(
    capital: 'Ciudad de Panamá', continente: 'América Central', habitantes: 4400000,
    ciudades: ['Ciudad de Panamá', 'San Miguelito', 'Tocumen', 'David', 'Colón'],
    clubes: ['Tauro FC', 'Plaza Amador', 'Alianza FC', 'CD Árabe Unido'],
    entrenador: 'Thomas Christiansen', rankingFifa: 43,
    curiosidades: [
      'Debutó en el Mundial 2018 tras clasificarse por primera vez en su historia',
      'El Canal de Panamá une los océanos Atlántico y Pacífico',
      'País con la mayor biodiversidad por km² del mundo',
      'El sombrero panamá es en realidad originario de Ecuador',
    ],
  ),
  'Sudáfrica': PaisData(
    capital: 'Pretoria', continente: 'África', habitantes: 60100000,
    ciudades: ['Johannesburgo', 'Ciudad del Cabo', 'Durban', 'Pretoria', 'Port Elizabeth'],
    clubes: ['Mamelodi Sundowns', 'Kaizer Chiefs', 'Orlando Pirates', 'SuperSport United'],
    entrenador: 'Hugo Broos', rankingFifa: 44,
    curiosidades: [
      'Anfitrión del Mundial 2010, primer país africano en organizarlo',
      'País con 11 idiomas oficiales, la mayor cantidad del mundo',
      'Nelson Mandela luchó contra el apartheid y fue presidente del país',
      'Patria de la vuvuzela, el instrumento que sonó en todo el Mundial 2010',
    ],
  ),
  'Bosnia Herzegovina': PaisData(
    capital: 'Sarajevo', continente: 'Europa', habitantes: 3300000,
    ciudades: ['Sarajevo', 'Banja Luka', 'Mostar', 'Tuzla', 'Zenica'],
    clubes: ['FK Sarajevo', 'FK Željezničar', 'NK Široki Brijeg', 'FK Zrinjski Mostar'],
    entrenador: 'Sergej Barbarez', rankingFifa: 45,
    curiosidades: [
      'Debutó en el Mundial 2014, su única participación hasta 2026',
      'Edin Džeko es el máximo goleador histórico con más de 60 goles',
      'País con tres grupos étnicos: bosnios, serbios y croatas conviviendo',
      'El Puente Viejo de Mostar es Patrimonio de la Humanidad de la UNESCO',
    ],
  ),
  'Cabo Verde': PaisData(
    capital: 'Praia', continente: 'África', habitantes: 600000,
    ciudades: ['Praia', 'Mindelo', 'Santa Maria', 'Assomada', 'São Filipe'],
    clubes: ['Sporting Clube da Praia', 'CS Mindelense', 'Académica do Fogo'],
    entrenador: 'Pedro Brito', rankingFifa: 46,
    curiosidades: [
      'La selección más pequeña por población del Mundial 2026',
      'Archipiélago de 10 islas volcánicas en el Atlántico frente a Senegal',
      'País conocido por la música de la morna y la famosa Cesária Évora',
      'A pesar de su pequeño tamaño, ha producido grandes futbolistas europeos',
    ],
  ),
  'Uzbekistán': PaisData(
    capital: 'Taskent', continente: 'Asia', habitantes: 36000000,
    ciudades: ['Taskent', 'Samarcanda', 'Bujará', 'Namangán', 'Andiyán'],
    clubes: ['FC Pakhtakor', 'FC Nasaf', 'FC Lokomotiv Tashkent', 'FC Navbahor'],
    entrenador: 'Srecko Katanec', rankingFifa: 47,
    curiosidades: [
      'Primera participación en un Mundial para este país de Asia Central',
      'Samarcanda fue una de las ciudades más importantes de la Ruta de la Seda',
      'País con una de las arquitecturas islámicas más bellas del mundo',
      'Uzbekistán fue parte de la Unión Soviética hasta 1991',
    ],
  ),
  'Nueva Zelanda': PaisData(
    capital: 'Wellington', continente: 'Oceanía', habitantes: 5100000,
    ciudades: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'],
    clubes: ['Auckland City FC', 'Wellington Phoenix', 'Team Wellington'],
    entrenador: 'Darren Bazeley', rankingFifa: 48,
    curiosidades: [
      'Los All Whites participaron en el Mundial 2010 sin perder ningún partido',
      'País conocido por el rugby (All Blacks) más que por el fútbol',
      'Escenario de El Señor de los Anillos gracias a sus paisajes únicos',
      'Los maoríes son el pueblo indígena de Nueva Zelanda con una cultura muy rica',
    ],
  ),
  'Rep. Dem. Congo': PaisData(
    capital: 'Kinshasa', continente: 'África', habitantes: 100000000,
    ciudades: ['Kinshasa', 'Lubumbashi', 'Mbuji-Mayi', 'Kananga', 'Kisangani'],
    clubes: ['TP Mazembe', 'AS Vita Club', 'DC Motema Pembe', 'AS Dauphin Noir'],
    entrenador: 'Sébastien Desabre', rankingFifa: 49,
    curiosidades: [
      'Como Zaire participó en el Mundial 1974, única aparición africana del país',
      'TP Mazembe es uno de los clubs más laureados de África',
      'País con la mayor selva tropical del mundo después del Amazonas',
      'El río Congo es el segundo más caudaloso del mundo tras el Amazonas',
    ],
  ),
  'Haití': PaisData(
    capital: 'Puerto Príncipe', continente: 'América Central', habitantes: 11400000,
    ciudades: ['Puerto Príncipe', 'Cap-Haïtien', 'Gonaïves', 'Les Cayes', 'Pétionville'],
    clubes: ['Violette AC', 'Racing Club Haïtien', 'Don Bosco FC', 'AS Capoise'],
    entrenador: 'Marc Collat', rankingFifa: 50,
    curiosidades: [
      'Primer país negro independiente del mundo (1804) tras la revolución esclava',
      'Participó en el Mundial 1974 en Alemania Occidental',
      'País con una cultura muy rica: vudú, compás y arte naïf famoso mundialmente',
      'A pesar de las dificultades, el fútbol es la pasión nacional',
    ],
  ),
  'Curazao': PaisData(
    capital: 'Willemstad', continente: 'América del Sur', habitantes: 150000,
    ciudades: ['Willemstad', 'Barber', 'Sint Michiel', 'Soto', 'Westpunt'],
    clubes: ['SV União', 'Centro Dominguito', 'Racing Club Curaçao'],
    entrenador: 'Remko Bicentini', rankingFifa: 51,
    curiosidades: [
      'Island del Caribe que forma parte del Reino de los Países Bajos',
      'Muchos de sus jugadores han nacido o crecido en los Países Bajos',
      'Famosa por sus playas de aguas cristalinas y la arquitectura colonial holandesa',
      'El papiamento es el idioma local, mezcla de portugués, español, neerlandés y lenguas africanas',
    ],
  ),
  'Jordania': PaisData(
    capital: 'Amán', continente: 'Asia', habitantes: 10800000,
    ciudades: ['Amán', 'Zarka', 'Irbid', 'Russeifa', 'Wadi as-Sir'],
    clubes: ['Al-Faisaly', 'Al-Wehdat', 'Al-Ramtha', 'Shabab Al-Ordon'],
    entrenador: 'Hossam Hassan', rankingFifa: 52,
    curiosidades: [
      'Primera participación de Jordania en un Mundial',
      'Petra, la ciudad rosa esculpida en roca, es una de las siete maravillas del mundo moderno',
      'El Mar Muerto, el punto más bajo de la Tierra, está en Jordania',
      'País conocido por su hospitalidad y el falafel como plato nacional',
    ],
  ),
};

PaisData? getPaisData(String nombreEspanol) {
  return kPaisesData[nombreEspanol];
}
